# Generated by Django 5.0.4 on 2024-04-18 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorCycleCoverDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='motocycle_insurance.basemodel')),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('log_book_no', models.CharField(max_length=100, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('manufacture_year', models.DateField()),
                ('engine_cc', models.CharField(max_length=100)),
                ('policy_details', models.JSONField(blank=True, null=True)),
                ('motorcycle_and_rider_details', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('motocycle_insurance.basemodel',),
        ),
    ]
