# Generated by Django 5.0.4 on 2024-04-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_basemodel_transactions'),
        ('insurance_packages', '0001_initial'),
        ('motocycle_insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcyclecoverdetails',
            name='package_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_packages.package'),
        ),
        migrations.AddField(
            model_name='motorcyclecoverdetails',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.transactions'),
        ),
    ]
