# Generated by Django 5.0.4 on 2024-05-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_packages', '0001_initial'),
        ('motocycle_insurance', '0003_motorvehicledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorvehicledetails',
            name='package_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_packages.package'),
        ),
    ]
