# Generated by Django 5.0.4 on 2024-05-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_basemodel_transactions'),
        ('motocycle_insurance', '0004_motorvehicledetails_package_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorvehicledetails',
            name='payment_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.transactions'),
        ),
    ]
