# Generated by Django 5.0.4 on 2024-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocycle_insurance', '0006_motorcyclecoverdetails_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehicledetails',
            name='manufacture_year',
            field=models.CharField(max_length=100),
        ),
    ]
