# Generated by Django 5.0.4 on 2024-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocycle_insurance', '0007_alter_motorvehicledetails_manufacture_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorvehicledetails',
            name='vehicle_use',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
