# Generated by Django 4.2.5 on 2024-06-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_created_at_and_more'),
        ('motocycle_insurance', '0009_alter_motorvehicledetails_package_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorvehicledetails',
            name='policy_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OtherPolicies',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='motocycle_insurance.basemodel')),
                ('policy_detatils', models.JSONField(blank=True, null=True)),
                ('policy_type', models.CharField(choices=[('Education Policy', 'Education Policy'), ('Home Insurance', 'Home Insurance'), ('Medical Cover', 'Medical Cover'), ('Individual Life Cover', 'Individual Life Cover'), ('Travel Insurance', 'Travel Insurance'), ('Golfers Insurance', 'Golfers Insurance'), ('Personal Accident', 'Personal Accident')], default='', max_length=25)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
            bases=('motocycle_insurance.basemodel',),
        ),
    ]
