# Generated by Django 5.0.3 on 2024-03-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name.', max_length=255)),
                ('short_name', models.CharField(help_text='Enter the short name.', max_length=255)),
                ('motto', models.CharField(help_text='Enter the company motto.', max_length=255)),
                ('email', models.EmailField(help_text='Enter the contact email.', max_length=254)),
                ('primary_phone', models.CharField(help_text='Enter the primary contact phone number.', max_length=255)),
                ('secondary_phone', models.CharField(help_text='Enter the secondary contact phone number.', max_length=255)),
                ('building', models.CharField(blank=True, help_text='Enter the location building', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Enter the location street', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='Enter the P.O Box', max_length=255)),
                ('city_name', models.CharField(blank=True, help_text='Enter the city name', max_length=255)),
                ('zip_code', models.CharField(blank=True, help_text='Enter the zip code', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Enter the facebook account url', max_length=255)),
                ('twitter_x', models.URLField(blank=True, help_text='Enter the X account url', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='Enter the Instagram account url', max_length=255)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the Linkedin account url', max_length=255)),
                ('tiktok', models.CharField(blank=True, help_text="Enter the organization's tiktok account url (Not required).", max_length=255)),
                ('whatsapp', models.URLField(blank=True, help_text="Enter the Whatsapp url in the format 'https://wa.me/254700000000'. Replace with appropriate phone number", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
