# Generated by Django 5.0.4 on 2024-06-28 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name.', max_length=255)),
                ('short_name', models.CharField(help_text='Enter the short name.', max_length=255)),
                ('motto', models.CharField(help_text='Enter the company motto.', max_length=255)),
                ('primary_email', models.EmailField(help_text='Enter the primary contact email.', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, help_text='Enter the secondary contact email.', max_length=254)),
                ('primary_phone', models.CharField(help_text='Enter the primary contact phone number.', max_length=255)),
                ('secondary_phone', models.CharField(blank=True, help_text='Enter the secondary contact phone number.', max_length=255)),
                ('building', models.CharField(blank=True, help_text='Enter the location building', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Enter the location street', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='Enter the P.O Box', max_length=255)),
                ('city_name', models.CharField(blank=True, help_text='Enter the city name', max_length=255)),
                ('zip_code', models.CharField(blank=True, help_text='Enter the zip code', max_length=255)),
                ('open_days', models.CharField(blank=True, help_text='e.g Monday - Friday', max_length=255)),
                ('open_hours', models.CharField(blank=True, help_text='e.g 8:15AM - 05:00PM', max_length=255)),
                ('twitter_x', models.URLField(blank=True, help_text='Enter the X account url', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Enter the facebook account url', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='Enter the Instagram account url', max_length=255)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the Linkedin account url', max_length=255)),
                ('tiktok', models.CharField(blank=True, help_text="Enter the organization's tiktok account url (Not required).", max_length=255)),
                ('whatsapp', models.URLField(blank=True, help_text="Enter the Whatsapp url in the format 'https://wa.me/254700000000'. Replace with appropriate phone number", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('document', models.FileField(upload_to='documents/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('amount', models.CharField(blank=True, max_length=255)),
                ('payment_number', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('base.basemodel',),
        ),
    ]
