# Generated by Django 5.0.4 on 2024-04-23 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_document'),
        ('users', '0003_alter_user_options_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('amount', models.CharField(blank=True, max_length=255)),
                ('payment_number', models.CharField(blank=True, max_length=255)),
                ('payment_status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('base.basemodel',),
        ),
    ]
