# Generated by Django 5.0.4 on 2024-05-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_basemodel_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='PENDING', max_length=10),
        ),
    ]
