# Generated by Django 5.0.4 on 2024-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idNumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='krapin',
            field=models.CharField(max_length=255),
        ),
    ]
