# Generated by Django 5.0.4 on 2024-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
