# Generated by Django 5.0.4 on 2024-06-29 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('premiums', models.CharField(max_length=255)),
                ('features', models.JSONField()),
                ('category', models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Motor', 'Motor')], default='default', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
